import Button from "@/components/Button";
import Container from "@/components/Container";
import Head from "next/head";

import Image from "next/image";
import heroImage from "/public/main-hero.jpg";
import { BsArrowRight } from "react-icons/bs";
export default function Home() {
  return (
    <>
      <Head>
        <title>CITY OF CASA || ARKANSAS</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container>
        <div className="font-poppins grid grid-cols-12 gap-8 py-16  items-center">
          <div className=" col-span-5 ">
            <h1 className=" font-bold text-6xl mb-8 ">
              Welcome to Casa, Arkansas.{" "}
            </h1>
            <div className=" flex gap-x-5 ">
              <Button
                link="/"
                className=" bg-casa-green "
                rightIcon={<BsArrowRight size={32} />}
              >
                Learn More
              </Button>
              <Button link="/news" className=" bg-casa-blue ">
                News & Events
              </Button>
            </div>
          </div>
          <div className=" col-span-7 relative">
            <div className=" h-80 mx-16 my-24 ">
              <Image
                alt="hero image"
                src={heroImage}
                objectFit="cover"
                objectPosition="center"
              />
            </div>
            <div className=" absolute h-full w-4/6 bg-casa-blue rounded-lg -z-10 right-0 top-0 "></div>
          </div>
        </div>
      </Container>
    </>
  );
}
